# DO NOT EDIT. This file is generated by update.sh
{ fetchFromGitHub }: {

  version = "6.0.1";

  cmake = fetchFromGitHub {
    owner = "KitWare";
    repo = "CMake";
    rev = "31f835410efeea50acd43512eb9e5646a26ea177";
    hash = "sha256-3RAmxoX2zaKlg2yj3fTWMfBhj0TFNdVKQfJyG0epVg4=";
  };

  cmark = fetchFromGitHub {
    owner = "swiftlang";
    repo = "swift-cmark";
    rev = "3ccff77b2dc5b96b77db3da0d68d28068593fa53";
    hash = "sha256-b/igbZbHFXK/SqS84UGWsUoVjChNFBb0t0w4HoPTguE=";
  };

  curl = fetchFromGitHub {
    owner = "curl";
    repo = "curl";
    rev = "d755a5f7c009dd63a61b2c745180d8ba937cbfeb";
    hash = "sha256-2sAnQKWk67MNR2pFQGDN1mQ6re+A9we3oPkM6bZAmYw=";
  };

  icu = fetchFromGitHub {
    owner = "unicode-org";
    repo = "icu";
    rev = "0e7b4428866f3133b4abba2d932ee3faa708db1d";
    hash = "sha256-Pf8wbeWyWOqdHQbOoTsHMktinUxdc8eXWrOLCqZ0IJU=";
  };

  indexstore-db = fetchFromGitHub {
    owner = "swiftlang";
    repo = "indexstore-db";
    rev = "f4d7f08f6a078050d86aed10a06bf1fc871a8ded";
    hash = "sha256-OP0+qCXc+Z5+Lz5h/1T6JvPbOjdoPEpZ7yGVWbWYxGw=";
  };

  libxml2 = fetchFromGitHub {
    owner = "gnome";
    repo = "libxml2";
    rev = "2b998a4ffbdfea04fc6a620721abc690a15743af";
    hash = "sha256-2SEzGhMeIHoHe9EKV6LgPLBXdmrxWWgnLYwUMZFWxNQ=";
  };

  llbuild = fetchFromGitHub {
    owner = "swiftlang";
    repo = "swift-llbuild";
    rev = "322a06adf86c9136baf53a503daeb837b3920885";
    hash = "sha256-OpYHGPV1LRdBrc3R2Bq1RLOq4flPwVzQLtrSLONKHO4=";
  };

  llvm-project = fetchFromGitHub {
    owner = "swiftlang";
    repo = "llvm-project";
    rev = "73500bf55acff5fa97b56dcdeb013f288efd084f";
    hash = "sha256-P0IEyQLcMkaL7lGOxq2GOQXn8q0pCsnW06RB4Lrq0io=";
  };

  ninja = fetchFromGitHub {
    owner = "ninja-build";
    repo = "ninja";
    rev = "a524bf3f6bacd1b4ad85d719eed2737d8562f27a";
    hash = "sha256-LvV/Fi2ARXBkfyA1paCRmLUwCh/rTyz+tGMg2/qEepI=";
  };

  sourcekit-lsp = fetchFromGitHub {
    owner = "swiftlang";
    repo = "sourcekit-lsp";
    rev = "480bb0c5328dab7350cbfcc9c1105a2cfd48a32f";
    hash = "sha256-m7LGHa2M2h4Ncbf18Eu5Mv8TGieoZ6HqOW1mToFtssY=";
  };

  swift = fetchFromGitHub {
    owner = "swiftlang";
    repo = "swift";
    rev = "01224689bf23d7eb20254ed6dfa99bd6200c2251";
    hash = "sha256-vTamy78oBccKFumQCSLiaBOijsBXZ0XWas1efaMELdI=";
  };

  swift-argument-parser = fetchFromGitHub {
    owner = "apple";
    repo = "swift-argument-parser";
    rev = "8f4d2753f0e4778c76d5f05ad16c74f707390531";
    hash = "sha256-qEJ329hqQyQVxtHScD7qPmWW9ZDf9bX+4xgpDlX0w5A=";
  };

  swift-asn1 = fetchFromGitHub {
    owner = "apple";
    repo = "swift-asn1";
    rev = "12c24ff59d541e5ef15116095445ce72b85cd0c6";
    hash = "sha256-66NK8Qw7A6JAGeRDHODEhRP8yoCewYwK7zYc1uB1j5g=";
  };

  swift-atomics = fetchFromGitHub {
    owner = "apple";
    repo = "swift-atomics";
    rev = "cd142fd2f64be2100422d658e7411e39489da985";
    hash = "sha256-Ho3/BDUwAVGG26u8Jz2j1mwqFRcLc+DTlqTyGelM+Gc=";
  };

  swift-certificates = fetchFromGitHub {
    owner = "apple";
    repo = "swift-certificates";
    rev = "01d7664523af5c169f26038f1e5d444ce47ae5ff";
    hash = "sha256-n5dE5J8f7PAVoJkIpiKrrDvB0xIil5VwtzC2mx6vz80=";
  };

  swift-cmark-gfm = fetchFromGitHub {
    owner = "swiftlang";
    repo = "swift-cmark";
    rev = "3ccff77b2dc5b96b77db3da0d68d28068593fa53";
    hash = "sha256-b/igbZbHFXK/SqS84UGWsUoVjChNFBb0t0w4HoPTguE=";
  };

  swift-collections = fetchFromGitHub {
    owner = "apple";
    repo = "swift-collections";
    rev = "3d2dc41a01f9e49d84f0a3925fb858bed64f702d";
    hash = "sha256-Lomz4BOsTN4MDKBL3pnfkbQQ6QelzUKE2Hw1YGUruZg=";
  };

  swift-corelibs-foundation = fetchFromGitHub {
    owner = "apple";
    repo = "swift-corelibs-foundation";
    rev = "59e6789524d8593320076e27e39b3852bacf20ca";
    hash = "sha256-Z0Z/0PV9PQ0XhB8TJl5Bgaz+jzyDKW0emVarQoMWpIw=";
  };

  swift-corelibs-libdispatch = fetchFromGitHub {
    owner = "apple";
    repo = "swift-corelibs-libdispatch";
    rev = "137b6cf3060eae87d9b367c263619c2eca5d3aac";
    hash = "sha256-vZ0JddR31wyFOjmSqEuzIJNBQIUgcLpjabbnlSF3LqY=";
  };

  swift-corelibs-xctest = fetchFromGitHub {
    owner = "apple";
    repo = "swift-corelibs-xctest";
    rev = "9c016d4e9e7981299a2b5625bdbee7b54462f591";
    hash = "sha256-99mEGgJF3zagFBNbPH1QeltTjqkdsfJYix14LWSKw1Q=";
  };

  swift-crypto = fetchFromGitHub {
    owner = "apple";
    repo = "swift-crypto";
    rev = "629f0b679d0fd0a6ae823d7f750b9ab032c00b80";
    hash = "sha256-lcB497b/T1bHShPrjNjHthrs76pDFpU+4uN0uW4tz+4=";
  };

  swift-docc = fetchFromGitHub {
    owner = "swiftlang";
    repo = "swift-docc";
    rev = "61f67ae2d1ece463090554578a4362e67333c55b";
    hash = "sha256-n52B+AQ/UYT1/sBpTdmKgXSJdjlK36KtLEwNxgn1KLQ=";
  };

  swift-docc-render-artifact = fetchFromGitHub {
    owner = "swiftlang";
    repo = "swift-docc-render-artifact";
    rev = "1fb693c552b157b24fb407cf5d5cf97c72f7cf47";
    hash = "sha256-kuf91cDvNXV1+zaED9Gmyq4FXKa1f13WeVEaDywsRic=";
  };

  swift-docc-symbolkit = fetchFromGitHub {
    owner = "swiftlang";
    repo = "swift-docc-symbolkit";
    rev = "2940bfa6217839402018ecc823ffd4457573859f";
    hash = "sha256-9bpbo4jfbAkfwp/Beu6PAFt2uY9BvY4h4ju1IFAHU/s=";
  };

  swift-driver = fetchFromGitHub {
    owner = "swiftlang";
    repo = "swift-driver";
    rev = "ddec3979d48b535ac647aec8b03d380cea0fc26a";
    hash = "sha256-AqvR6Sk3ifUvpTMmEL4e+1RWWewlZyceJhRZShWhOcc=";
  };

  swift-experimental-string-processing = fetchFromGitHub {
    owner = "swiftlang";
    repo = "swift-experimental-string-processing";
    rev = "420a8c24e71a8581d1d30c41927c3a21c4077aeb";
    hash = "sha256-lK/teda9uti2vRSOBHY0OklnEsrv46RYnlw5/qNDl5w=";
  };

  swift-format = fetchFromGitHub {
    owner = "swiftlang";
    repo = "swift-format";
    rev = "58f07e3aeca179d202ba4991976a83687d64307f";
    hash = "sha256-xBE4/ttVQWOXzTH/Hc0efRPTRT1V56rwja3rMwV2Mmk=";
  };

  swift-foundation = fetchFromGitHub {
    owner = "apple";
    repo = "swift-foundation";
    rev = "6864318d7ef25931b34da076f828657ea4e566b6";
    hash = "sha256-Np02wloNRW2G1UjIB3Wxuy4XDw9osD2Utdqe2hLiapU=";
  };

  swift-foundation-icu = fetchFromGitHub {
    owner = "apple";
    repo = "swift-foundation-icu";
    rev = "be50023b7b3e8142f08768dbeebf9712240fb653";
    hash = "sha256-GURX4O42HQJW38jLlTyc1TmLWHSaDfn7IagHMV3/XIY=";
  };

  swift-installer-scripts = fetchFromGitHub {
    owner = "swiftlang";
    repo = "swift-installer-scripts";
    rev = "55231d5ed9f58c13277a5e7c49a7d20e3c9d2037";
    hash = "sha256-dQuGgl27V06t1XKEMBmfUiU65Ug4oiJiEmkYBjvltX8=";
  };

  swift-integration-tests = fetchFromGitHub {
    owner = "swiftlang";
    repo = "swift-integration-tests";
    rev = "874bd0f5b0fa23c18f601d9bdd1dded34e6637ea";
    hash = "sha256-FP40EeNwlL8sL2kVIpjuPcFp4cfx6PGQSSFNvQepuVU=";
  };

  swift-llvm-bindings = fetchFromGitHub {
    owner = "swiftlang";
    repo = "swift-llvm-bindings";
    rev = "680142b5179e43dbb6f1f0db42009b76a6f13b88";
    hash = "sha256-zaEmzuQZLskIZuWeyJLOZc4hGTU7t0wWLjnGrRz2NYo=";
  };

  swift-lmdb = fetchFromGitHub {
    owner = "swiftlang";
    repo = "swift-lmdb";
    rev = "c42582487fe84f72a4d417dd2d8493757bd4d072";
    hash = "sha256-zcnteU8c+iGaUBxWYT9IDbHrdAE12HDlgy1MwdAk1Pk=";
  };

  swift-markdown = fetchFromGitHub {
    owner = "swiftlang";
    repo = "swift-markdown";
    rev = "907674c2ae2d24c32fba50101821b1a7fdd291e2";
    hash = "sha256-vvbnoEV6CLJe7y8q25Cfp6ak1a+HLEwBJWgZHJnH9hU=";
  };

  swift-nio = fetchFromGitHub {
    owner = "apple";
    repo = "swift-nio";
    rev = "1d425b0851ffa2695d488cce1d68df2539f42500";
    hash = "sha256-FscOA/S7on31QCR/MZFjg4ZB3FGJ+rdptZ6MRZJXexE=";
  };

  swift-nio-ssl = fetchFromGitHub {
    owner = "apple";
    repo = "swift-nio-ssl";
    rev = "2e74773972bd6254c41ceeda827f229bccbf1c0f";
    hash = "sha256-5QGkmkCOXhG3uOdf0bd3Fo1MFekB8/WcveBXGhtVZKo=";
  };

  swift-numerics = fetchFromGitHub {
    owner = "apple";
    repo = "swift-numerics";
    rev = "0a5bc04095a675662cf24757cc0640aa2204253b";
    hash = "sha256-D4cOMa26NYhVzRz3le5CPydn9qEFbFLAqgonPRB0cVo=";
  };

  swift-stress-tester = fetchFromGitHub {
    owner = "swiftlang";
    repo = "swift-stress-tester";
    rev = "2f54b42c054de02099e9ed0c887f7c6da2073dab";
    hash = "sha256-zYgM3Q/+6WaTD9RcIt/VFKJfaQgRL89W9fcTVIwiufc=";
  };

  swift-syntax = fetchFromGitHub {
    owner = "swiftlang";
    repo = "swift-syntax";
    rev = "515f79b522918f83483068d99c68daeb5116342d";
    hash = "sha256-bpv8FjgRXt6dNw7Ys46V7VoT04ASG7uQbQAPJWZZd1M=";
  };

  swift-system = fetchFromGitHub {
    owner = "apple";
    repo = "swift-system";
    rev = "f9266c85189c2751589a50ea5aec72799797e471";
    hash = "sha256-m8ZryRuaaXqw1jpBNhw5rw0AgragnsH1BxDi7tRsjOk=";
  };

  swift-testing = fetchFromGitHub {
    owner = "swiftlang";
    repo = "swift-testing";
    rev = "324940967b09dbbd06055e70c6016b83bc9389cf";
    hash = "sha256-LEonohtch/XsHXMxKfeUxRtWQS5dDK4d2hm5f9TrLhA=";
  };

  swift-tools-support-core = fetchFromGitHub {
    owner = "swiftlang";
    repo = "swift-tools-support-core";
    rev = "3e5d9c81a087832dffba0e4914ceb98caca594ea";
    hash = "sha256-2AZVIq22vvyXZhxzZcx4sv9qbzX3E8jwCJXAZZZZYm8=";
  };

  swift-xcode-playground-support = fetchFromGitHub {
    owner = "apple";
    repo = "swift-xcode-playground-support";
    rev = "bbba1ba704c37d1d0131bb7d6986a80ad8cb6d6c";
    hash = "sha256-esv5h1SLs/oy7hr4CwhnHufwlBxu2Q+gfbTYU/LlkyE=";
  };

  swiftpm = fetchFromGitHub {
    owner = "swiftlang";
    repo = "swift-package-manager";
    rev = "dd22b6ef16315fcdcb07c1f86bd608598f102e20";
    hash = "sha256-xYG2tbY5f9yfJk7zmlGSyFHPwTf0/bk3dLkZAsx2MZg=";
  };

  wasi-libc = fetchFromGitHub {
    owner = "WebAssembly";
    repo = "wasi-libc";
    rev = "1dfe5c302d1c5ab621f7abf04620fae92700fd22";
    hash = "sha256-Km0HPHXFfN373zW+jdND7vB4/R589uXPe5KcvmAN+nw=";
  };

  wasmkit = fetchFromGitHub {
    owner = "swiftwasm";
    repo = "WasmKit";
    rev = "6dfc20ab07e9c8c8e1a7f76462516c20413f2526";
    hash = "sha256-fX41ehcUnTMnwqTEGqxp9+SZ80q4yBdPQhBo/SQ3AL4=";
  };

  yams = fetchFromGitHub {
    owner = "jpsim";
    repo = "Yams";
    rev = "0d9ee7ea8c4ebd4a489ad7a73d5c6cad55d6fed3";
    hash = "sha256-AY/fIvB7THrl9GWzGJL8eDBbkcLw27tSRTGtUqmYw8k=";
  };

  zlib = fetchFromGitHub {
    owner = "madler";
    repo = "zlib";
    rev = "09155eaa2f9270dc4ed1fa13e2b4b2613e6e4851";
    hash = "sha256-eUuXV5zfy+fmiMNdWw5QCqDloBkaxy1tgi7by9nYHNA=";
  };

}
